/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-25 23:50:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class accountDelete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>会員脱退</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header\r\n");
      out.write("\t\tstyle=\"width: 900px; display: flex; justify-content: center; align-items: center; margin: 50px auto 0 auto;\">\r\n");
      out.write("\t\t<img src=\"logo.png\" alt=\"logo\" width=\"70\" height=\"70\">\r\n");
      out.write("\t\t<h1 style=\"padding-top: 20px; margin-left: 12px; color: hotpink;\">\r\n");
      out.write("\t\t\t<span style=\"font-size: 0.8em; color: gray;\">株式会社</span>神田ユニフォーム\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<table align=\"left\" style=\"padding-bottom: 5px; padding-left: 10%;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout\"\r\n");
      out.write("\t\t\t\tstyle=\"text-decoration: none; color: gray; font-weight: 900;\">【ログイン】</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<hr size=\"8\" color=\"LightPink\" width=\"90%\"></hr>\r\n");
      out.write("\r\n");
      out.write("\t<h2 style=\"text-align: center; color: gray; padding-top: 20px;\">会員脱退</h2>\r\n");
      out.write("\t<form style=\"margin-top: 20px;\"\r\n");
      out.write("\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/accountDelete\" method=\"post\"\r\n");
      out.write("\t\tonsubmit=\"return call();\">\r\n");
      out.write("\t\t<table style=\"margin: 0 auto; border-spacing: 8px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th style=\"width: 80; color: gray;\">氏名</th>\r\n");
      out.write("\t\t\t\t<td><input\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 220px; height: 22px; border-radius: 12px; border: 3px solid pink; outline: none;\"\r\n");
      out.write("\t\t\t\t\ttype=text size=\"25\" id=\"name1\" name=\"name\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th style=\"width: 80; color: gray;\">パスワード</th>\r\n");
      out.write("\t\t\t\t<td><input\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 220px; height: 22px; border-radius: 12px; border: 3px solid pink; outline: none;\"\r\n");
      out.write("\t\t\t\t\ttype=password size=\"25\" id=\"pw\" name=\"pw\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th style=\"width: 80; color: gray;\">メールアドレス</th>\r\n");
      out.write("\t\t\t\t<td><input\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 220px; height: 22px; border-radius: 12px; border: 3px solid pink; outline: none;\"\r\n");
      out.write("\t\t\t\t\ttype=text size=\"25\" id=\"email\" name=\"email\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=2 style=\"text-align: center;\"><input\r\n");
      out.write("\t\t\t\t\tstyle=\"margin-top: 30px; background: none; border-radius: 8px; border: 3px solid pink; padding: 2px 6px; color: gray; font-weight: 900;\"\r\n");
      out.write("\t\t\t\t\ttype=\"submit\" value=\"会員脱退\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t<h4 style=\"text-align: center;\">");
      out.print(request.getAttribute("cmd"));
      out.write("</h4>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction isEmpty(input) {\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn !input.value;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction checkSpace(str) {\r\n");
      out.write("\t\t\tif (str.search(/\\s/) !== -1) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tlet u_email = document.getElementById('email');\r\n");
      out.write("\t\tlet u_name = document.getElementById('name1');\r\n");
      out.write("\t\tlet u_pw = document.getElementById('pw');\r\n");
      out.write("\r\n");
      out.write("\t\tfunction call() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (isEmpty(u_name) || checkSpace(u_name.value)) {\r\n");
      out.write("\t\t\t\talert(\"名前を確認してください。\");\r\n");
      out.write("\t\t\t\tu_name.value = \"\";\r\n");
      out.write("\t\t\t\tu_name.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (isEmpty(u_pw) || checkSpace(u_pw.value)) {\r\n");
      out.write("\t\t\t\talert(\"パスワードを確認してください。\");\r\n");
      out.write("\t\t\t\tu_pw.value = \"\";\r\n");
      out.write("\t\t\t\tu_pw.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (isEmpty(u_email) || checkSpace(u_email.value)) {\r\n");
      out.write("\t\t\t\talert(\"メールアドレスを確認してください。\");\r\n");
      out.write("\t\t\t\tu_email.value = \"\";\r\n");
      out.write("\t\t\t\tu_email.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet result = confirm('削除しますか？');\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn result;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
