/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-28 00:46:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.Account;

public final class accountUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.Account");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Account a = (Account) session.getAttribute("accountList");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>会員情報変更画面</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<header\r\n");
      out.write("\t\t\tstyle=\"width: 900px; display: flex; justify-content: center; align-items: center; margin: 50px auto 0 auto;\">\r\n");
      out.write("\t\t\t<img src=\"https://postfiles.pstatic.net/MjAyMzA2MjdfMjcy/MDAxNjg3ODMxMTk3NzMx.y2U6FThvXwdOi9XToRwE2N4H_hRXqdkBoCeK2m9852Mg.qxG3IdUM9aHf2hR4frt1B7kkSVwn5eb_OthgeJAIE04g.PNG.hyh3700/logo.png?type=w773\" alt=\"logo\" width=\"70\" height=\"70\">\r\n");
      out.write("\t\t\t<h1 style=\"padding-top: 20px; margin-left: 12px; color: hotpink;\">\r\n");
      out.write("\t\t\t\t<span style=\"font-size: 0.8em; color: gray;\">株式会社</span>神田ユニフォーム\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t<table align=\"left\" style=\"padding-bottom: 5px; padding-left: 10%;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\"><a\r\n");
      out.write("\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/view/menu.jsp\"\r\n");
      out.write("\t\t\t\tstyle=\"text-decoration: none; color: gray; font-weight: 900;\">【メニュー】</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<hr size=\"8\" color=\"LightPink\" width=\"90%\"></hr>\r\n");
      out.write("\r\n");
      out.write("\t<h2 style=\"padding-top: 20px; text-align: center; color: gray;\">会員情報変更</h2>\r\n");
      out.write("\t<form method=\"post\" onsubmit=\"return call();\"\r\n");
      out.write("\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/accountUpdate\"\r\n");
      out.write("\t\tstyle=\"margin: 70px auto 200px auto; display: flex; flex-direction: column; align-items: center; justify-content: space-between; height: 180px;\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"display: flex; justify-content: space-between; width: 700px;\">\r\n");
      out.write("\t\t\t<table style=\"text-align: center; width: 500px; height: 50px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; color: hotpink; padding: 6;\"><<変更前情報>></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #C0C0C0; width: 110\">氏名</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width: 80\">");
      out.print(a.getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #C0C0C0;\">住所</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(a.getAddress());
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #C0C0C0;\">ユーザーID</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(a.getEmail());
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #C0C0C0;\">パスワード</td>\r\n");
      out.write("\t\t\t\t\t<td>英文字・数字・記号(8文字以上)</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"background-color: #C0C0C0;\">パスワード確認</td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; color: hotpink; padding: 0;\"><<変更後情報>></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"name\" value=\"");
      out.print(a.getName());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 12px; border: 3px solid pink; outline: none;\"\r\n");
      out.write("\t\t\t\t\t\ttype=text size=\"25\" name=\"name\"></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"address\" value=\"");
      out.print(a.getAddress());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 12px; border: 3px solid pink; outline: none;\"\r\n");
      out.write("\t\t\t\t\t\ttype=text size=\"25\" name=\"address\"></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(a.getEmail());
      out.write("<input id=\"email\" value=\"");
      out.print(a.getEmail());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 12px; border: 3px solid pink; outline: none;\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" size=\"25\" placeholder=\"メールアドレス\" name=\"email\"></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"pw\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 12px; border: 3px solid pink; outline: none;\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" size=\"25\" name=\"pw\"></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"pwCheck\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 12px; border: 3px solid pink; outline: none;\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" size=\"25\" name=\"pwCheck\"></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<h4 style=\"text-align: center;\">");
      out.print(request.getAttribute("cmd"));
      out.write("</h4>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(a.getId());
      out.write("\"> <input\r\n");
      out.write("\t\t\tstyle=\"margin-top: 90px; background: none; border: 3px solid pink; padding: 4px 6px; border-radius: 8px;\"\r\n");
      out.write("\t\t\ttype=\"submit\" value=\"変更完了\">\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction isEmpty(input) {\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn !input.value;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tfunction lessThan(input, length) {\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn input.value.length < length;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction moreThan(input, length) {\r\n");
      out.write("\t\t\treturn input.value.length > length;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tfunction containKr(input) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet ok = \"qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890@._/\";\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (let i = 0; i < input.value.length; i++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (ok.indexOf(input.value[i]) == -1) {\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction equalData(input1, input2) {\r\n");
      out.write("\t\t\treturn !(input1.value == input2.value)\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\tfunction notContains(input, set) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tfor (let i = 0; i < set.length; i++) {\r\n");
      out.write("\t\t\t\tif (input.value.indexOf(set[i]) != -1)\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction notCheck(input) {\r\n");
      out.write("\t\t\tif (input.checked) {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction isNotNumber(input) {\r\n");
      out.write("\t\t\treturn isNaN(input.value);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction isNotType(input, type) {\r\n");
      out.write("\t\t\ttype = \".\" + type; //.jpg\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn input.value.indexOf(type) == -1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar pattern_spc = /[~!@#$%^&*()_+|<>?:{}]/;\r\n");
      out.write("\r\n");
      out.write("\t\tfunction checkKor(str) {\r\n");
      out.write("\t\t\tconst regExp = /[ㄱ-ㅎㅏ-ㅣ가-힣]/g;\r\n");
      out.write("\t\t\tif (regExp.test(str)) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction checkNum(str) {\r\n");
      out.write("\t\t\tconst regExp = /[0-9]/g;\r\n");
      out.write("\t\t\tif (regExp.test(str)) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction checkEng(str) {\r\n");
      out.write("\t\t\tconst regExp = /[a-zA-Z]/g;\r\n");
      out.write("\t\t\tif (regExp.test(str)) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction checkEngNum(str) {\r\n");
      out.write("\t\t\tconst regExp = /[a-zA-Z0-9]/g;\r\n");
      out.write("\t\t\tif (regExp.test(str)) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction checkSpace(str) {\r\n");
      out.write("\t\t\tif (str.search(/\\s/) !== -1) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction CheckID(uid) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (!/^[a-zA-Z0-9]{8,20}$/.test(uid)) {\r\n");
      out.write("\t\t\t\talert(\"ユーザーIDは8文字以上の英文字・数字・記号の組み合わせのみ入力できます。\");\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar chk_num = uid.search(/[0-9]/g);\r\n");
      out.write("\t\t\tvar chk_eng = uid.search(/[a-z]/ig);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (chk_num < 0 || chk_eng < 0) {\r\n");
      out.write("\t\t\t\talert(\"ユーザーIDは小文字のみ入力できます。\");\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (/(\\w)\\1\\1\\1/.test(uid)) {\r\n");
      out.write("\t\t\t\talert(\"ユーザーIDは4回以上連続文字は入力できません。\");\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction CheckPassword(upw) {\r\n");
      out.write("\t\t\tvar chk_num = upw.search(/[0-9]/g);\r\n");
      out.write("\t\t\tvar chk_eng = upw.search(/[a-z]/ig);\r\n");
      out.write("\t\t\tvar chk_special = upw\r\n");
      out.write("\t\t\t\t\t.search(/(?=.*[a-zA-ZS])(?=.*?[#?!@$%^&*-]).{8,20}/);\r\n");
      out.write("\t\t\tif (chk_num < 0 || chk_eng < 0 || chk_special < 0) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (/(\\w)\\1\\1\\1/.test(upw)) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction equalCheck(input1, input2) {\r\n");
      out.write("\t\t\tif (input1.value != input2.value) {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tlet u_name = document.getElementById('name');\r\n");
      out.write("\t\tlet u_address = document.getElementById('address');\r\n");
      out.write("\t\tlet u_email = document.getElementById('email');\r\n");
      out.write("\t\tlet u_pw = document.getElementById('pw');\r\n");
      out.write("\t\tlet u_pwCheck = document.getElementById('pwCheck');\r\n");
      out.write("\r\n");
      out.write("\t\tfunction call() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (isEmpty(u_name) || lessThan(u_name, 2) || moreThan(u_name, 20)\r\n");
      out.write("\t\t\t\t\t|| checkNum(u_name.value) || checkSpace(u_name.value)\r\n");
      out.write("\t\t\t\t\t|| (pattern_spc.test(u_name.value))) {\r\n");
      out.write("\t\t\t\talert(\"氏名を確認してください。\");\r\n");
      out.write("\t\t\t\tu_name.value = \"\";\r\n");
      out.write("\t\t\t\tu_name.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (isEmpty(u_address) || checkSpace(u_address.value)) {\r\n");
      out.write("\t\t\t\talert(\"住所を確認してください。\");\r\n");
      out.write("\t\t\t\tu_address.value = \"\";\r\n");
      out.write("\t\t\t\tu_address.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (isEmpty(u_email) || checkSpace(u_email.value)) {\r\n");
      out.write("\t\t\t\talert(\"ユーザーIDを確認してください。\");\r\n");
      out.write("\t\t\t\tu_email.value = \"\";\r\n");
      out.write("\t\t\t\tu_email.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (isEmpty(u_pw) || lessThan(u_pw, 8) || checkSpace(u_pw.value)\r\n");
      out.write("\t\t\t\t\t|| checkKor(u_pw.value) || CheckPassword(u_pw.value)) {\r\n");
      out.write("\t\t\t\talert(\"パスワードを正しい形式で入力してください。\");\r\n");
      out.write("\t\t\t\tu_pw.value = \"\";\r\n");
      out.write("\t\t\t\tu_pw.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (equalCheck(u_pw, u_pwCheck)) {\r\n");
      out.write("\t\t\t\talert(\"パスワードを確認してください。\");\r\n");
      out.write("\t\t\t\tu_pwCheck.value = \"\";\r\n");
      out.write("\t\t\t\tu_pwCheck.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet result = confirm('変更しますか？');\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn result;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
